spring:
  application:
    name: item
  autoconfigure:
    exclude: # prevent loading mongo config unless profile-based configuration defines it (because of flapdoodle).
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration
server:
  port: 8080
